name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql: ["5.7", "8"]
        distribution: ["debian:buster", "ubuntu:focal", "ubuntu:bionic"]
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env:
        MYSQL_VERSION: ${{ matrix.mysql }}
        DISTRIBUTION: ${{ matrix.distribution }}
      run: script/cibuild
