name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build:
    name: ${{ format('Build ({0}, {1}, {2})', matrix.mysql, matrix.distribution, matrix.ruby) }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql: ["5.7", "8"]
        distribution: ["debian:buster", "ubuntu:focal", "ubuntu:bionic"]
        include:
          - ruby: "2.8"
          - ruby: "3.2"
          - ruby: "1.9"
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: echo $GITHUB_TOKEN | docker login ghcr.io --username trilogy --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      env:
        MYSQL_VERSION: ${{ matrix.mysql }}
        DISTRIBUTION: ${{ matrix.distribution }}
        RUBY_VERSION: ${{ matrix.ruby }}
      run: script/cibuild
